apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-certificate
  namespace: redis
spec:
  secretName: redis-certificate
  issuerRef:
    name: internal-clusterissuer
    kind: ClusterIssuer
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - localhost
  ipAddresses:
    - 127.0.0.1